@startuml
left to right direction

actor :Utente\n(Operatore o Autista): as utente

rectangle "Sistema Gestione Parcheggio"{
    usecase "Registra Ingresso Auto" as ingresso
    usecase "Registra Uscita Auto" as uscita
    usecase "Mostra avviso/Errore" as errore
    usecase " Visualizza Stato Parcheggio" as stato
}

utente --> ingresso
utente --> uscita
utente --> stato

ingresso ..> errore : "<<exclude>>\n(Se parcheggio pieno)"
ingresso ..> stato : "<<include>>"
uscita ..> errore : "<<exclude>>\n(Se posto non valido)"
uscita ..> stato : "<<include>>"
@enduml