@startuml
actor "Utente" as utente
participant "Interfaccia(HTML/DOM)" as interfaccia
participant "Logica(parcheggio.js)" as logica

utente -> interfaccia : Clicca "Fai entrare un'auto"
activate interfaccia

interfaccia -> logica : entraAuto()
activate logica
note right: Inizia il ciclo for sull'array
logica -> logica : Cerca il primo 0 nell'array

alt Posto libero trovato
    logica -> logica : parcheggio[i] = 1
    logica -> interfaccia : alert("Auto parcheggiata!")
    logica -> logica : aggiornaSchermo()
    note right: Sostituisce la spunta verde con la X rossa

    logica -> interfaccia : innerHTML = nuovo HTML con immagini
else Nessun posto libero(Tutti 1)
    logica -> interfaccia : alert("Parcheggio Pieno!")
end    
deactivate logica
interfaccia --> utente : Mostra il parcheggio aggiornato a schermo
deactivate interfaccia





@enduml