@startuml
[*] --> Libero
Libero --> Occupato : entraAuto()\n[Se viene trovato questo posto libero]
Occupato --> Libero : esceAuto()\n[Se l'utente conferma col prompt/confirm]
Libero: Valore JS: parcheggio[i] = 0
Libero: DOM: ( Cannot decode )
Occupato: Valore JS: parcheggio[i] = 1
Occupato: DOM: ( Cannot decode )
@enduml